#
# Copyright 2026 ABSA Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Test
on:
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]

jobs:
  qa:
    runs-on: ubuntu-latest
    name: QA (Black, Pylint, mypy, Pytest)
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.14'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -e packages/core[dev]
          pip install -e packages/datasets_pdf[dev]
          pip install -e packages/adapters/collector_gh[dev]
          pip install -e packages/services/normalize_issues[dev]
          pip install -e "apps/cli[dev]"

      - name: Run QA checks (Black, Pylint, mypy, Pytest)
        run: make py-qa
